version: '3'

services:
  jenkins:
    image: jenkins/jenkins:2.387.2
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/New_York"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins-data: